[project]
name = "sys-insta"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.16",
    "pillow>=11.2.1",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]
